## 内置tomcat
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB


## 配置数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foo?userUnicode=true&charactorEncoding=UTF-8
    username: root
    password: root
  hikari:
    connect-timeout: 30000 # 等待连接池分配时间的最长时间
    minimum-idle: 5 # 最小连接数
    maximum-pool-size: 20 # 最大连接数，处理器x2向上取整
    auto-commit: true
    idel-timeout: 600000 # 连接超时时间
    pool-name: DateSourceHikariCP # 连接池名字
    max-lifetime: 1800000 # 连接的生命时间，超时未被使用被释放
    connection-test-query: SELECT 1

## mybatis 配置
mybatis:
  type-aliases-package: com.orange.pojo
  mapper-locations: classpath:mapper/*.xml

## mybatis mapper 配置
mapper:
  mappers: com.foo.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL